config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'
  get 'contacts/create'
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords'
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'root#top'

    get 'search/:genre' => 'bikes#search_genre', as: 'search_genre'

    get 'users/withdraw' => 'users#withdraw', as: 'withdraw'
    get 'users/unsubscribe' => 'users#unsubscride', as: 'unsubscride'
    get 'about', to: 'root#about'
    get 'privacy_policy',to:'root#privacy_policy'
    get 'terms_of_service', to: 'root#terms_of_service'
    get 'complited', to: 'contacts#complited', as: 'complited'
  resources :contacts, only:[:new, :create]

  resources :users, only: [:show, :edit, :update, :destroy]
  resources :makers, only: [:index, :show] do
    resources :maker_favorites, only:[:create, :destroy]

    resources :bikes, only:[:show] do
      resources :impressions, only:[:create, :destroy, :edit, :update]
      resource :bike_favorites, only:[:create, :destroy]
    end
  end
  get 'search' => 'bikes#search_bike', as: 'search_bike'

    if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  namespace :admin do
    resources :users, only: [:index, :show, :update, :destroy]

    resources :makers do
      get 'bikes/:id' => 'bikes#show', as: 'bike_show'
      delete 'bikes/:id' => 'bikes#destroy',as: 'bike_destroy'
      get 'bikes/:id/edit' =>'bikes#edit', as: 'bike_edit'
      patch 'bikes/:id' => 'bikes#update',as: 'bike_update'
        get 'bikes/:bike_id/years_bikes/new' => 'years_bikes#new', as: 'years_bike_new'
        post 'bikes/:bike_id/years_bikes' => 'years_bikes#create', as: 'years_bike_create'
        get 'bikes/:bike_id/years_bikes/:id/:year/edit' => 'years_bikes#edit', as: 'years_bike_edit'
        patch 'bikes/:bike_id/years_bikes/:id/:year' => 'years_bikes#update', as: 'years_bike_update'
        delete 'bikes/:bike_id/years_bikes/:id/:year' => 'years_bikes#destroy', as: 'years_bike_destroy'
  end

    get 'search' => 'bikes#search_bike', as: 'search_bike'
    get 'bikes/new'
    post 'bikes/create'

    resources :impressions, only: [:destroy]

  end

end

app/models/bike.rb
class Bike < ApplicationRecord
  has_many :bike_favorites, dependent: :destroy
  has_many :years_bikes, dependent: :destroy
  has_many :impressions, dependent: :destroy
  belongs_to :maker

  attachment :bike_image
  acts_as_taggable
  acts_as_taggable_on :tags

#お気に入りしているかどうか
  def favorited_by?(user)
    bike_favorites.where(user_id: user.id).exists?
  end

  enum genre: { aero: 0, allround: 1, endurance: 2 }
  enum grade: { entry: 0, middle: 1, highend: 2, flagship: 3 }

  ransacker :genre, formatter: proc {|v| sym = Bike.genres_i18n.invert[v]
    genres[sym]}
  ransacker :grade, formatter: proc {|v| sym = Bike.grades_i18n.invert[v]
    grades[sym]}

validates :bike_name, presence: true
validates :bike_name_kana, presence: true
validates :bike_image, presence: true
validates :genre, presence: true
validates :grade, presence: true

end

app/controllers/admin/bikes_controller.rb
class Admin::BikesController < ApplicationController
  before_action :authenticate_admin!
  def new
  	@bike = Bike.new
  end

  def create
    @bike = Bike.new(bike_params)
    if @bike.save
      redirect_to admin_maker_bike_show_path(@bike.maker_id, @bike.id)
    else
      render :new
    end
  end

  def show
    @bike = Bike.find(params[:id])
    @user = User.find_by(id: params[:id])
    @impressions = @bike.impressions.page(params[:page]).per(10)
   if @bike.impressions.blank?
      @reviews = [@bike.impressions.average(:design_evaluation).to_f, @bike.impressions.average(:weight_evaluation).to_f, @bike.impressions.average(:rigidity_evaluation).to_f, @bike.impressions.average(:comfort_evaluation).to_f, @bike.impressions.average(:cp_evaluation).to_f]
    else
      @reviews = [@bike.impressions.average(:design_evaluation).floor(1).to_f, @bike.impressions.average(:weight_evaluation).floor(1).to_f, @bike.impressions.average(:rigidity_evaluation).floor(1).to_f, @bike.impressions.average(:comfort_evaluation).floor(1).to_f, @bike.impressions.average(:cp_evaluation).floor(1).to_f]
  end
end

  def edit
    @bike = Bike.find(params[:id])
  end

  def update
    @bike = Bike.find(params[:id])
    if @bike.update(bike_params)
       redirect_to admin_maker_bike_show_path(@bike.maker_id, @bike.id)
    else
      render :edit
    end
  end

  def destroy
    @bike = Bike.find(params[:id])
    @maker = @bike.maker
    @bike.destroy
    redirect_to admin_maker_path(@maker)
  end

    def search_bike
    if params[:tag_name]
       @bikes = Bike.tagged_with("#{params[:tag_name]}").page(params[:page]).per(50)
    elsif params[:q].nil?
      @bikes = Bike.page(params[:page]).per(50)
    else
       @q = Bike.includes(:maker, :years_bikes).ransack(search_params)
       @bikes = @q.result(distinct: true).page(params[:page]).per(50)
    end
  end

  private
    def search_params
      params.require(:q).permit!
    end

  def bike_params
    params.require(:bike).permit(:bike_name, :bike_name_kana, :bike_image, :bike_body, :tag_list, :genre, :grade, :maker_id)
  end
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController

  def show
    @bike = Bike.find(params[:id])
    @bike_id = @bike.id
    @years_bikes = @bike.years_bikes
    @impression = Impression.new
    @impressions = @bike.impressions.page(params[:page]).per(10)
    @review = Impression.find_by(id: params[:id])


    if params[:year]
      year = params[:year].to_i
      @recent_years_bikes = YearsBike.where(year: year)
    else
     @recent_years_bikes = YearsBike.where(year: @bike.years_bikes.maximum(:year))
    end

    @recentbike = @recent_years_bikes.to_a.select do |bike|
     bike.bike_id == @bike.id
    end
    @recentbike = @recentbike[0]

    if @bike.impressions.blank?
       @reviews = [@bike.impressions.average(:design_evaluation).to_f, @bike.impressions.average(:weight_evaluation).to_f, @bike.impressions.average(:rigidity_evaluation).to_f, @bike.impressions.average(:comfort_evaluation).to_f, @bike.impressions.average(:cp_evaluation).to_f]
    else
       @reviews = [@bike.impressions.average(:design_evaluation).floor(1).to_f, @bike.impressions.average(:weight_evaluation).floor(1).to_f, @bike.impressions.average(:rigidity_evaluation).floor(1).to_f, @bike.impressions.average(:comfort_evaluation).floor(1).to_f, @bike.impressions.average(:cp_evaluation).floor(1).to_f]
    end

  end

  def search_bike
    if params[:tag_name]
       @bikes = Bike.tagged_with("#{params[:tag_name]}").page(params[:page]).per(50)
    elsif params[:q].nil?
      @bikes = Bike.page(params[:page]).per(50)
    else
       @q = Bike.includes(:maker, :years_bikes).ransack(search_params)
       @bikes = @q.result(distinct: true).page(params[:page]).per(50)
    end
  end

   def search_genre
    @bikes = Bike.where(genre: params[:genre])
  end


private
  def search_params
    params.require(:q).permit!
  end

end

app/helpers/admin/bikes_helper.rb
module Admin::BikesHelper
end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/views/admin/bikes/_bike_image_fields.html.erb
<div class="nested-fields">
  <%= f.hidden_field :id %>
  <%= f.number_field :display_order, placeholder: "画像表示順", class: 'form-control' %>
  <%= f.attachment_field :image %>
  <%= link_to_remove_association '削除', f, class: 'btn btn-info text-center' %>
</div>

app/views/admin/bikes/_tag-list.html.erb
<% tag_list.each do |tag| %>
  <%= link_to admin_search_bike_path(tag_name: tag), class:"text-white" do %>
    <span class="badge badge-primary"><%= tag %></span>
  <% end %>
<% end %>

app/views/admin/bikes/edit.html.erb
<%=render 'layouts/admin-header', q: @q %>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-lg-8">
      <h2>バイク情報編集</h2>
      <%= form_for([@bike.maker, @bike], url: admin_maker_bike_update_path(@bike),html: {method: "patch"}) do |f| %>
          <%= f.text_field :bike_name, placeholder: "バイク名", class:"form-control" %>
          <%= f.text_field :bike_name_kana, placeholder: "バイク名読み方", class:"form-control" %>
          <%= f.collection_select :maker_id, Maker.all, :id, :maker_name %><br>
          <%= f.select :genre, [["エアロ", 'aero'],["オールラウンド", 'allround'],["エンデュランス", 'endurance']], class:"form-control" %><br>
          <%= f.select :grade, [["エントリー", 'entry'],["ミドル", 'middle'],["ハイエンド", 'highend'],["フラグシップ", 'flagship']], class:"form-control" %><br>
          <%= f.text_field :tag_list, value: @bike.tag_list.join(','), class:"form-control",placeholder: "タグを入力してください。区切りは「,」で行えます。" %>
          <%= f.submit "この内容でバイクを保存する", class:"btn btn-primary text-center" %>
      <% end %>
        </div>
    </div>
  </div>
</div>
<%=render 'layouts/footer' %>

app/views/admin/bikes/new.html.erb
<%=render 'layouts/admin-header', q: @q %>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-lg-8">
      <h2>バイク新規登録</h2>
      <%= form_for @bike, :url => {:action => :create} do |f| %>
        <%= f.attachment_field :bike_image %>
          <%= f.text_field :bike_name, placeholder: "バイク名", class:"form-control" %>
          <%= f.text_field :bike_name_kana, placeholder: "バイク名読み方", class:"form-control" %>
          <%= f.collection_select :maker_id, Maker.all, :id, :maker_name %>
          <%= f.select :genre, [["エアロ","aero"],["オールラウンド","allround"],["エンデュランス","endurance"]], class:"form-control" %>
          <%= f.select :grade, [["エントリー","entry"],["ミドル","middle"],["ハイエンド","highend"],["フラグシップ","flagship"]], class:"form-control" %>
          <%= f.text_field :tag_list, value: @bike.tag_list.join(','), class:"form-control",placeholder: "タグを入力してください。区切りは「,」で行えます。" %>
          <%= f.submit "この内容でバイクを保存する", class:"btn btn-primary text-center" %>
      <% end %>
        </div>
    </div>
  </div>
</div>
<%= render 'layouts/page-up' %>
<%=render 'layouts/footer' %>

app/views/admin/bikes/search_bike.html.erb
<%=render 'layouts/admin-header', q: @q %>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-lg-12">
      <div class="search-area">
        <%= search_form_for(@q, url: admin_search_bike_path, html: {method: "get"}) do |f| %>
        <h3>バイク詳細検索</h3>
        <div></div>
        <%= f.collection_select :maker_id_eq, Maker.all, :id, :maker_name, :include_blank => '指定なし' %>
        <%= f.select :genre_eq, [["エアロ", "エアロ"],["オールラウンド","オールラウンド"],["エンデュランス","エンデュランス"]], :include_blank => '指定なし'%>
        <%= f.select :grade_eq, [["エントリー", "エントリー"],["ミドル","ミドル"],["ハイエンド","ハイエンド"],["フラグシップ","フラグシップ"]], :include_blank => '指定なし'%>
        <%= f.search_field :bike_name_or_bike_name_kana_cont, placeholder: 'メーカー名またはバイク名で検索' %>
        <%= f.submit "検索", class:"btn btn-default" %>
        <% end %>
      </div>
    </div>
    <div class="col-sm-12 col-lg-12 bike-index">
      <h3>検索でヒットしたバイク一覧</h3>
    </div>
    <% @bikes.each do |bike|%>
    <div class="col-sm-6 col-lg-3 bike-image">
      <%= render "admin/bikes/tag-list", tag_list: bike.tag_list, maker: @maker %>
      <br>
      <%= link_to admin_maker_bike_show_path(bike.maker_id,bike.id) do %>
      <%= attachment_image_tag bike, :bike_image, format:'jpeg', size: "200x125", fallback:"/images/no_image(2).jpg", size:"200x125" %>
      <br>
      <% end %>
      <%= bike.bike_name %>
      <br>
      <%= bike.bike_name_kana %>
    </div>
    <% end %>
    <%= paginate @bikes, class: "paginate" %>
  </div>
</div>
<%= render 'layouts/page-up' %>
<%= render "layouts/footer" %>

app/views/admin/bikes/show.html.erb
<%=render 'layouts/admin-header', q: @q %>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-lg-12">
      <h2>
        <%= @bike.bike_name %>
        <br>
        <%= @bike.bike_name_kana %>
      </h2>
      <%= attachment_image_tag @bike,:bike_image, format:'jpeg', size: "800x500", fallback:"/images/no_image(2).jpg", size:"800x500" %>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>年度</th>
            <th>モデル画像</th>
            <th>概要</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <% @bike.years_bikes.each do |years_bike|%>
            <td>
              <%= years_bike.year %>
            </td>
            <% years_bike.years_bike_images.each_with_index do |years_bike_image, i| %>
            <% if years_bike_image.display_order == 1 %>
            <td class="row small-image-list">
              <div class="col">
                <%= attachment_image_tag years_bike_image, :image, format:'jpeg', size: "100x62", fallback:"/images/no_image(2).jpg", size:"100x62", class:"small-image" %>
              </div>
              <% else %>
              <div class="col">
                <%= attachment_image_tag years_bike_image, :image, format:'jpeg', size: "100x62", fallback:"/images/no_image(2).jpg", size:"100x62", class:"small-image" %>
              </div>
              <% if (i == years_bike.years_bike_images.size - 1) %>
            </td>
            <% end %>
            <% end %>
            <% end %>
            <td>
              <%= years_bike.year_bike_body.truncate(20) %>
            </td>
            <td>

              <%= link_to "編集",admin_maker_years_bike_edit_path(@bike.maker_id,@bike.id, years_bike.id, year: years_bike.year), class:"btn btn-warning" %>
              <%= link_to "削除", admin_maker_years_bike_destroy_path(@bike.maker, @bike.id, years_bike.id, year: years_bike.year), method: :delete, class: "btn btn-danger", "data-confirm" => "本当に削除しますか？"%>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <%= link_to "年度情報を追加する",admin_maker_years_bike_new_path(@bike.maker_id,@bike.id), class:"btn btn-primary" %>
      <%= link_to "このバイクを編集する", admin_maker_bike_edit_path, class:"btn btn-warning" %>
      <%= link_to "このバイクを削除する", admin_maker_bike_destroy_path(@bike.maker,@bike.id), method: :delete, class: "btn btn-danger", "data-confirm" => "本当に削除しますか？"%>

      <% if @reviews.all?{|e| e.nil?} %>
        <h3 class="review-area">このバイクにはまだインプレッションがありません。</h3>
        <% else %>
      <h3>インプレッション</h3>
      <canvas id="myChart" style ="width:200px, height:200px;"></canvas>
      <% @bike.impressions.each do |impression| %>
      <div class="impression-area">
        <div class="balloon5 d-flex">
          <div>
            <%= impression.user.name%>
            <%= link_to admin_user_path(impression.user.id) do %>
            <%= attachment_image_tag impression.user, :profile_image, format:"jpeg", size:"80x80", fallback: "/images/no_image(1).jpg",:class => "head-user-icon"%>
            <% end %>
          </div>
          <div class="chatting">
            <div class="says">
              <b>
                <%= impression.impression_title %>
              </b>　　　　　　　　　　　　　　　　　　　　
              <%= impression.created_at.strftime("%Y/%m/%d/ %H:%M") %>
              <br>
              <p style="display: inline-block;">総合評価：
                <div class="satisfaction_star-rate-<%= impression.id %>" style="display: inline-block;"></div>
              </p>
              <p style="display: inline-block;">デザイン評価：
                <div class="design_star-rate-<%= impression.id %>" style="display: inline-block;"></div>
              </p>
              <p style="display: inline-block;">重量評価：
                <div class="weight_star-rate-<%= impression.id %>" style="display: inline-block;"></div>
              </p>
              <p style="display: inline-block;">剛性評価：
                <div class="rigidity_star-rate-<%= impression.id %>" style="display: inline-block;"></div>
              </p>
              <p style="display: inline-block;">快適性評価：
                <div class="comfort_star-rate-<%= impression.id %>" style="display: inline-block;"></div>
              </p>
              <p style="display: inline-block;">コストパフォーマンス評価：
                <div class="cp_star-rate-<%= impression.id %>" style="display: inline-block;"></div>
              </p>
              <% if impression.impression_text.lines.count > 4 %>
              <div class="grad-warp">
                <span class="grad-trigger"></span>
                <div class="grad-item">
                  <%= simple_format(impression.impression_text) %>
                </div>
              </div>
              <% else %>
              <%= simple_format(impression.impression_text) %>
              <% end %>
              <script>
                        $('.satisfaction_star-rate-<%= impression.id %>').raty({
                          size: 36,
                          starOff:  '<%= asset_path('/images/star-off.png') %>',
                          starOn : '<%= asset_path('/images/star-on.png') %>',
                          readOnly: true,
                          score: <%=impression.satisfaction_level %>
                        });

                        $('.design_star-rate-<%= impression.id %>').raty({
                          size: 36,
                          starOff:  '<%= asset_path('/images/star-off.png') %>',
                          starOn : '<%= asset_path('/images/star-on.png') %>',
                          readOnly: true,
                          score: <%=impression.design_evaluation %>
                        });

                        $('.weight_star-rate-<%= impression.id %>').raty({
                          size: 36,
                          starOff:  '<%= asset_path('/images/star-off.png') %>',
                          starOn : '<%= asset_path('/images/star-on.png') %>',
                          readOnly: true,
                          score: <%=impression.weight_evaluation %>
                        });

                        $('.rigidity_star-rate-<%= impression.id %>').raty({
                          size: 36,
                          starOff:  '<%= asset_path('/images/star-off.png') %>',
                          starOn : '<%= asset_path('/images/star-on.png') %>',
                          readOnly: true,
                          score: <%=impression.rigidity_evaluation %>
                        });

                        $('.comfort_star-rate-<%= impression.id %>').raty({
                          size: 36,
                          starOff:  '<%= asset_path('/images/star-off.png') %>',
                          starOn : '<%= asset_path('/images/star-on.png') %>',
                          readOnly: true,
                          score: <%=impression.comfort_evaluation %>
                        });

                        $('.cp_star-rate-<%= impression.id %>').raty({
                          size: 36,
                          starOff:  '<%= asset_path('/images/star-off.png') %>',
                          starOn : '<%= asset_path('/images/star-on.png') %>',
                          readOnly: true,
                          score: <%=impression.cp_evaluation %>
                        });
                      </script>
              <%= link_to "削除",  maker_bike_impression_path(@bike.maker,@bike.id, impression.id), method: :delete, class:"btn btn-danger btn-sm" %>
            </div>
          </div>
        </div>
      </div>
      <% end %>
      <% end %>
      <%= paginate @impressions, class: "paginate" %>
    </div>
  </div>
</div>
<%= render 'layouts/page-up' %>
<%= render "layouts/footer" %>

<script>
    $(document).on('turbolinks:load', function(){
      // 要素が見つからない場合、ここでガードする
      var element = document.getElementById("myChart");
      if(!element) { return }

      var ctx = element.getContext('2d');
      var myChart = new Chart(ctx, {
          type: 'radar',
          data: {
              labels: ["デザイン", "重量", "剛性", "快適性", "コストパフォーマンス"],
              datasets: [{
                  label: 'ユーザーの平均評価',
                  data: <%= @reviews %>,
                  backgroundColor: [
                      'rgba(144, 238, 144, 0.2)',
                  ],
                  borderColor: [
                      'rgba(75, 192, 192, 1)',
                  ],
                  borderWidth: 1
              }]
          },
          options: {
              title: {
                fontSize: 25,
                display: true,
                text: 'ユーザー評価'
              },
              scale: {
                      ticks: {
                        stepSize: 1,
                        suggestedMax: 5,
                        suggestedMin: 0,
                        callback: function(value, index, values){
                        return  value +  'つ星'
                          beginAtZero:true
                       }
                      }
                }
              }
            }
        }

    );
  })
</script>

<script>
$(document).on('turbolinks:load', function(){
  var url = $('#small1').attr("src");
  $('#big-image').attr("src", url);
});
</script>
<script>
var itemHeights = [];
var returnHeight;
$(document).on('turbolinks:load', function () {
  $(".grad-item").each(function () { //ターゲット(縮めるアイテム)
    var thisHeight = $(this).height(); //ターゲットの高さを取得
    itemHeights.push(thisHeight); //それぞれの高さを配列に入れる
    $(this).addClass("is-hide"); //CSSで指定した高さにする
    returnHeight = $(this).height(); //is-hideの高さを取得
  });
});
$(document).on('turbolinks:load', function () {
  $(".grad-trigger").on({
    'click': (function () { //トリガーをクリックしたら
      if (!$(this).hasClass("is-show")) {
        var index = $(this).index(".grad-trigger"); //トリガーが何個目か
        var addHeight = itemHeights[index]; //個数に対応する高さを取得
        $(this).addClass("is-show").next().animate({
          height: addHeight
        }, 200).removeClass("is-hide"); //高さを元に戻す
      } else {
        $(this).removeClass("is-show").next().animate({
          height: returnHeight
        }, 200).addClass("is-hide"); //高さを制限する
      }
    })
  });
});
</script>