config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'
  get 'contacts/create'
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords'
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'root#top'

    get 'search/:genre' => 'bikes#search_genre', as: 'search_genre'

    get 'users/withdraw' => 'users#withdraw', as: 'withdraw'
    get 'users/unsubscribe' => 'users#unsubscride', as: 'unsubscride'
    get 'about', to: 'root#about'
    get 'privacy_policy',to:'root#privacy_policy'
    get 'terms_of_service', to: 'root#terms_of_service'
    get 'complited', to: 'contacts#complited', as: 'complited'
  resources :contacts, only:[:new, :create]

  resources :users, only: [:show, :edit, :update, :destroy]
  resources :makers, only: [:index, :show] do
    resources :maker_favorites, only:[:create, :destroy]

    resources :bikes, only:[:show] do
      resources :impressions, only:[:create, :destroy, :edit, :update]
      resource :bike_favorites, only:[:create, :destroy]
    end
  end
  get 'search' => 'bikes#search_bike', as: 'search_bike'

    if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  namespace :admin do
    resources :users, only: [:index, :show, :update, :destroy]

    resources :makers do
      get 'bikes/:id' => 'bikes#show', as: 'bike_show'
      delete 'bikes/:id' => 'bikes#destroy',as: 'bike_destroy'
      get 'bikes/:id/edit' =>'bikes#edit', as: 'bike_edit'
      patch 'bikes/:id' => 'bikes#update',as: 'bike_update'
        get 'bikes/:bike_id/years_bikes/new' => 'years_bikes#new', as: 'years_bike_new'
        post 'bikes/:bike_id/years_bikes' => 'years_bikes#create', as: 'years_bike_create'
        get 'bikes/:bike_id/years_bikes/:id/:year/edit' => 'years_bikes#edit', as: 'years_bike_edit'
        patch 'bikes/:bike_id/years_bikes/:id/:year' => 'years_bikes#update', as: 'years_bike_update'
        delete 'bikes/:bike_id/years_bikes/:id/:year' => 'years_bikes#destroy', as: 'years_bike_destroy'
  end

    get 'search' => 'bikes#search_bike', as: 'search_bike'
    get 'bikes/new'
    post 'bikes/create'

    resources :impressions, only: [:destroy]

  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :impressions, dependent: :destroy
  has_many :maker_favorites, dependent: :destroy
  has_many :user_favorites, dependent: :destroy
  has_many :bike_favorites, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attachment :profile_image
  enum caution: { normal: 0, caution: 1, warning: 2, discipline: 3 }

    ransacker :caution, formatter: proc {|v| sym = User.cautions_i18n.invert[v]
    cautions[sym]}
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  def index
    if params[:p].nil?
      @p = User.ransack
      @users = User.all
      else
      @p = User.ransack(search_params)
      @users = @p.result(distinct: true)
    end
  end

  def show
    @user = User.find(params[:id])
    @impressions = @user.impressions.page(params[:page]).per(10)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path
  end

  def update
    @user = User.find(params[:id])
    @user.update
    redirect_to admin_users_path
  end

      private
    def search_params
      params.require(:p).permit!
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
    @impressions = @user.impressions.page(params[:page]).per(10)
  end

  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
       redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    login_id = current_user.id
    if @user.update(user_params)
       redirect_to user_path(@user.id)
    else render :edit
    end
  end
  
  def withdraw
    
  end

  def unsubscride
    
  end

  def destroy
  	@user = User.find(params[:id])
    @user.destroy
    redirect_to unsubscride_path
  end

private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction, :email)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<section class="slice slice-lg sct-color-1">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">

                <div class="form-user style-1 rounded has-shadow-1">
                    <div class="form-header">
                        <h2 class="form-header-title">ユーザー情報　編集</h2></div>

                      <div class="form-body">
                        <div class="row">
                        <div class="col-xs-12">

                          <%= form_for(@user) do |f| %>
                          <div class="form-group has-icon text-center">
                            <label class="control-label sr-only" for="inputfhandlename"></label>
                            <%= attachment_image_tag @user, :profile_image,fallback: "/images/no_image(1).jpg",  size:"150x150" %>
                            <%= f.attachment_field :profile_image %>
                          </div>

                          <div class="form-group has-icon">
                            <label class="control-label" for="inputfname">ユーザー名</label>
                            <%= f.text_field :name, autofocus: true, class:"form-control", id:"inputnane", placeholder:"ユーザー名"%>
                          </div>

                          <div class="form-group has-icon">
                            <label class="control-label" for="inputfintroduction">自己紹介</label>
                            <%= f.text_area :introduction, autofocus: true, class:"form-control", id:"inputintroduction", placeholder:"自己紹介を入力してください。"%>
                          </div>

                          <div class="form-group has-icon">
                            <label class="control-label" for="inputfmail">メールアドレス</label>
                            <%= f.email_field :email, autofocus: true, class:"form-control", id:"inputemail", placeholder:"メールアドレス"%>
                          </div>

                          <div class="form-group has-icon">
                          <%= f.submit "登録内容を変更する", class:"form-control btn btn-primary" %></div>
                          <div class="form-group has-icon">
                          <%= link_to"パスワード変更に進む", edit_user_registration_path , class:"btn btn-success" %>
                          <%= link_to"退会ページに進む", withdraw_path , class:"btn btn-danger" %></div>
                      <% end %>
                    </div>

                    </div>


                  </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/users/show.html.erb
<%= render 'layouts/header',q: @q %>
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-lg-3">
        <h3>マイページ</h3>
        <%= attachment_image_tag @user, :profile_image, size: '180x180', fallback: "/images/no_image(1).jpg" %>
          <h4 class="text-center">
            <%= @user.name %>
          </h4>
      </div>
      <div class="col-sm-6 col-lg-6">
        <div class="callout1-left">
          <p>
            <%= simple_format@user.introduction %>
          </p>
        </div>
        <% if @user == current_user %>
        <%= link_to "編集", edit_user_path(@user.id), class:"btn btn-success" %>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12 col-lg-12">
        <h3>お気に入りメーカー</h3>
        <% if @user.maker_favorites.empty? %>
        <br><h5>お気に入りメーカーはありません。<br> 気に入ったメーカーがあったらお気に入り登録してみてください！</h5><br>
          <% else %>
            <% @user.maker_favorites.each do |maker_favorite| %>
              <div class="col-sm-6 col-lg-4">
                <%= link_to maker_path(maker_favorite.maker_id) do %>
                  <%= attachment_image_tag maker_favorite.maker, :maker_image, size: "150x75", fallback:"/images/no_image(2).jpeg" %>
                    <% end %>
                      <%= maker_favorite.maker.maker_name %>
              </div>
              <% end %>
                <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12 col-lg-12">
        <h3>お気に入りバイク</h3>
        <% if @user.bike_favorites.empty? %>
        <br><h5>お気に入りバイクはありません。<br> 気に入ったバイクがあったらお気に入り登録してみてください！</h5><br>
          <% else %>
            <% @user.bike_favorites.each do |bike_favorite| %>
              <div class="col-sm-6 col-lg-4">
                <%= link_to maker_bike_path(bike_favorite.bike.maker_id,bike_favorite.bike.id) do %>
                  <%= attachment_image_tag bike_favorite.bike, :bike_image, size: "150x100", fallback:"/images/no_image(2).jpeg" %>
                    <% end %>
                      <%= bike_favorite.bike.maker.maker_name %>
                        <%= bike_favorite.bike.bike_name %>
              </div>
              <% end %>
                <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12 col-lg-12">
        <h3>インプレッション一覧</h3>
        <% if @user.impressions.empty? %>
          <br><h5>インプレッションはありません。<br>ぜひインプレッションしてみてくださいね！</h5><br>
          <% else %>
        <% @user.impressions.each do |impression| %>
          <div class="impression-area">
            <div class="balloon5 d-flex">
              <%= link_to maker_bike_path(impression.bike.maker_id,impression.bike.id) do %>
                <%= attachment_image_tag impression.bike, :bike_image, size: "150x100", fallback:"/images/no_image(2).jpeg" %>
                  <% end %>
                    <div class="chatting">
                      <div class="says" style="max-width: 500px; min-width: 500px;">
                        <%= impression.bike.bike_name %><br>
                          <%= impression.bike.bike_name_kana %>
                            </br>
                            レビュータイトル：<b><%= impression.impression_title %></b><br>
                              <p style="display: inline-block;">総合評価：
                                <div class="satisfaction_star-rate-<%= impression.id %>" style="display: inline-block;"></div>
                              </p>
                              <%= impression.created_at.strftime("%Y/%m/%d/ %H:%M") %>
                                <script>
                                  $('.satisfaction_star-rate-<%= impression.id %>').raty({
                                    size: 36,
                                    starOff:  '<%= asset_path('/images/star-off.png') %>',
                                    starOn : '<%= asset_path('/images/star-on.png') %>',
                                    readOnly: true,
                                    score: <%=impression.satisfaction_level %>
                                  });
                                </script>
                      </div>
                    </div>
            </div>
          </div>
          <% end %>
          <% end %>
          <%= paginate @impressions, class: "paginate" %>
      </div>
    </div>
  </div>
  <%= render 'layouts/page-up' %>
  <%= render 'layouts/footer' %>

app/views/users/unsubscride.html.erb
<%=render 'layouts/header', q: @q %>
<div class="container">
    <section class="row">
    	 <section class="col-sm-12 col-lg-12">
    	 	<div class="alert alert-warning text-center" role="alert">
    	 		<h2>退会が完了しました</h2>
    	 		<p>今までご利用いただき、誠にありがとうございました。<br>
		 		これからも是非、Road-Impressionをご利用くださいませ</p>
    	 	</div>
		 </section>
 </section>
</div>
<%= render "layouts/footer" %>

app/views/users/withdraw.html.erb
<%= render 'layouts/header',q: @q %>
<div class="container">
    <section class="row">
    	 <section class="col-sm-12 col-lg-12">
			<div class="alert alert-danger text-center" role="alert">
				<h2>退会前に必ずお読みください</h2><br>
				<p >本サイトから退会すると、会員向けサービスが全てご利用いただけなくなります。<br>
				※インプレッション情報は削除されません。退会後はインプレッションの編集・削除はできなくなります。※<br>
				必要に応じてインプレッションの編集・削除を行ったうえで退会をお願いします。</p>
				<%= link_to "退会する", user_path(current_user.id), class:"alert-link btn btn-danger", method: :delete, "data-confirm" => "本当に退会しますか？" %>
			</div>
		</section>
 </section>
</div>
<%= render "layouts/footer" %>