config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'
  get 'contacts/create'
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords'
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'root#top'

    get 'search/:genre' => 'bikes#search_genre', as: 'search_genre'

    get 'users/withdraw' => 'users#withdraw', as: 'withdraw'
    get 'users/unsubscribe' => 'users#unsubscride', as: 'unsubscride'
    get 'about', to: 'root#about'
    get 'privacy_policy',to:'root#privacy_policy'
    get 'terms_of_service', to: 'root#terms_of_service'
    get 'complited', to: 'contacts#complited', as: 'complited'
  resources :contacts, only:[:new, :create]

  resources :users, only: [:show, :edit, :update, :destroy]
  resources :makers, only: [:index, :show] do
    resources :maker_favorites, only:[:create, :destroy]

    resources :bikes, only:[:show] do
      resources :impressions, only:[:create, :destroy, :edit, :update]
      resource :bike_favorites, only:[:create, :destroy]
    end
  end
  get 'search' => 'bikes#search_bike', as: 'search_bike'

    if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  namespace :admin do
    resources :users, only: [:index, :show, :update, :destroy]

    resources :makers do
      get 'bikes/:id' => 'bikes#show', as: 'bike_show'
      delete 'bikes/:id' => 'bikes#destroy',as: 'bike_destroy'
      get 'bikes/:id/edit' =>'bikes#edit', as: 'bike_edit'
      patch 'bikes/:id' => 'bikes#update',as: 'bike_update'
        get 'bikes/:bike_id/years_bikes/new' => 'years_bikes#new', as: 'years_bike_new'
        post 'bikes/:bike_id/years_bikes' => 'years_bikes#create', as: 'years_bike_create'
        get 'bikes/:bike_id/years_bikes/:id/:year/edit' => 'years_bikes#edit', as: 'years_bike_edit'
        patch 'bikes/:bike_id/years_bikes/:id/:year' => 'years_bikes#update', as: 'years_bike_update'
        delete 'bikes/:bike_id/years_bikes/:id/:year' => 'years_bikes#destroy', as: 'years_bike_destroy'
  end

    get 'search' => 'bikes#search_bike', as: 'search_bike'
    get 'bikes/new'
    post 'bikes/create'

    resources :impressions, only: [:destroy]

  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bike.rb
class Bike < ApplicationRecord
  has_many :bike_favorites, dependent: :destroy
  has_many :years_bikes, dependent: :destroy
  has_many :impressions, dependent: :destroy
  belongs_to :maker

  attachment :bike_image
  acts_as_taggable
  acts_as_taggable_on :tags

#お気に入りしているかどうか
  def favorited_by?(user)
    bike_favorites.where(user_id: user.id).exists?
  end

  enum genre: { aero: 0, allround: 1, endurance: 2 }
  enum grade: { entry: 0, middle: 1, highend: 2, flagship: 3 }

  ransacker :genre, formatter: proc {|v| sym = Bike.genres_i18n.invert[v]
    genres[sym]}
  ransacker :grade, formatter: proc {|v| sym = Bike.grades_i18n.invert[v]
    grades[sym]}

validates :bike_name, presence: true
validates :bike_name_kana, presence: true
validates :bike_image, presence: true
validates :genre, presence: true
validates :grade, presence: true

end

app/models/bike_favorite.rb
class BikeFavorite < ApplicationRecord
  belongs_to :user
  belongs_to :bike
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true, length: {maximum:255},
                    format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}
  validates :message, presence: true
  validates :name, presence: true
end

app/models/impression.rb
class Impression < ApplicationRecord
  belongs_to :user
  belongs_to :bike
  has_many :user_favorites

  validates :satisfaction_level, presence: true
  validates :design_evaluation, presence: true
  validates :weight_evaluation, presence: true
  validates :rigidity_evaluation, presence: true
  validates :comfort_evaluation, presence: true
  validates :cp_evaluation, presence: true
  validates :impression_title, presence: true
  validates :impression_text, presence: true


  def favorited_by(user)
  	favorites.where(user_id: user.id).exists?
  	
  end
end

app/models/maker.rb
class Maker < ApplicationRecord
  has_many :bikes, dependent: :destroy
  has_many :maker_favorites, dependent: :destroy
  attachment :maker_image

   def favorited_by?(user)
    maker_favorites.where(user_id: user.id).exists?
  end

  validates :maker_name, presence: true
  validates :maker_image, presence: true
  validates :body, presence: true
  validates :country, presence: true

end

app/models/maker_favorite.rb
class MakerFavorite < ApplicationRecord
  belongs_to :user
  belongs_to :maker
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :impressions, dependent: :destroy
  has_many :maker_favorites, dependent: :destroy
  has_many :user_favorites, dependent: :destroy
  has_many :bike_favorites, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attachment :profile_image
  enum caution: { normal: 0, caution: 1, warning: 2, discipline: 3 }

    ransacker :caution, formatter: proc {|v| sym = User.cautions_i18n.invert[v]
    cautions[sym]}
end

app/models/user_favorite.rb
class UserFavorite < ApplicationRecord
  belongs_to :user
  belongs_to :impression
end

app/models/years_bike.rb
class YearsBike < ApplicationRecord
  belongs_to :bike
  has_many :years_bike_images, dependent: :destroy
  accepts_nested_attributes_for :years_bike_images, allow_destroy: true

  validates :year, presence: true
  validates :year_bike_body, presence: true

end

app/models/years_bike_image.rb
class YearsBikeImage < ApplicationRecord
  belongs_to :years_bike
  attachment :image

  validates :display_order, presence: true
  validates :image, presence: true
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?
 
    html = ""
    messages = resource.errors.full_messages.each do |errmsg|
      html += <<-EOF
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">close</span>
        </button>
        #{errmsg}
      </div>
      EOF
    end
    html.html_safe
  end
 
  def devise_error_messages?
    resource.errors.empty? ? false : true
  end
 
end

app/helpers/impressions_helper.rb
module ImpressionsHelper
end

app/helpers/makers_helper.rb
module MakersHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/_admin-header.html.erb

<header class="navbar navbar-expand-sm header" style="background-color: #FFFFFF;">
  <nav class="nav navbar-nav bavbar-left">
    <%= link_to admin_users_path do %>
      <%= image_tag "/images/logo.png",size: "200x100", :class => "logo-img" %>
    <% end %>
    <h1 class="header-title">管理者ページ</h1>
    <ul class="nav navbar-nav">
          <%= search_form_for(q, url: admin_search_bike_path, html: {method: "get"}) do |f| %>
            <%= f.search_field :bike_name_or_bike_name_kana_or_maker_maker_name_or_genre_cont, placeholder: 'メーカー名またはバイク名で検索', class:"form-control search-window" %>
            <%= f.submit "検索", class:"btn btn-default search-botton" %>
            <% end %>
      <div id="sp-menu">
        <h3 class="text-center" style="margin-top: 30px;">MENU</h3>
        <li>
          <%= link_to "ユーザー一覧", admin_users_path, class:"hm-link text-center" %>
        </li>
        <li>
          <%= link_to "メーカー一覧", admin_makers_path, class:"hm-link text-center" %>
        </li>
        <li>
          <%= link_to "メーカー新規登録", new_admin_maker_path, class:"hm-link text-center" %>
        </li>
        <li>
          <%= link_to "バイク新規登録", admin_bikes_new_path, class:"hm-link text-center" %>
        </li>
　      <li>
          <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class:"hm-link text-center" %>
        </li>
      </ul>
    </div>
  </nav>
  <div id="hm-icon">
   <%= link_to "#", class:"menu-trigger link" do %>
     <span></span>
     <span></span>
     <span></span>
   <% end %>
  </div>
</header>

app/views/layouts/_footer.html.erb
<footer>
    <div class="row">
      <div class="col-sm-12 col-lg-12 text-center text-white" style="background-color: gray;">
        <h3>Have a Good Ride !!</h3>
        <p>©Road-Impression.</p>
        <p>当サイトのすべてのコンテンツ・画像の無断利用を固く禁止致します。</p>
        <div class="text-center">
          <%= link_to "利用規約", terms_of_service_path, class:"about" %>
          <%= link_to "プライバシーポリシー", privacy_policy_path, class:"about" %>
          <%= link_to "お問い合わせ", new_contact_path, class:"about "%>
        </div>
      </div>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-expand-sm header" style="background-color: #FFFFFF;">
  <nav class="nav navbar-nav bavbar-left">
    <%= link_to root_path do %>
      <%= image_tag "/images/logo.png",size: "200x100", :class => "logo-img" %>
    <% end %>
              <%= search_form_for(q, url: search_bike_path, html: {method: "get"}) do |f| %>
            <%= f.search_field :bike_name_or_bike_name_kana_or_maker_maker_name_or_genre_cont, placeholder: 'メーカー名またはバイク名で検索', class:"form-control search-window" %>
            <%= f.submit "検索", class:"btn btn-default search-botton" %>
            <% end %>
    <% if user_signed_in? %>
        <div>
          <%= link_to user_path(current_user.id) do %>
            <%= attachment_image_tag current_user, :profile_image, format:"jpeg", size:"80x80", fallback: "/images/no_image(1).jpg",class:"head-user-icon float-left"%>
          <% end %>
        </div>
        <% end %>
      </nav>
      <nav>
        <ul class="nav navbar-nav">
      <div id="sp-menu">
        <h3 class="text-center" style="margin-top: 30px;">MENU</h3>
        <% if user_signed_in? %>
          <li class="hm-link text-center"><%= link_to "このサイトについて",about_path,class:"hm-link text-center" %></li>
          <li class="hm-link text-center"><%= link_to "ロードバイク詳細検索", search_bike_path, class:"hm-link text-center" %></li>
          <li class="hm-link text-center"><%= link_to "メーカー一覧", makers_path, class:"hm-link text-center" %></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"hm-link text-center" %></li>
        <% else %>
          <li><%= link_to "新規登録", new_user_registration_path,class:"hm-link text-center" %></li>
          <li><%= link_to "ログイン", new_user_session_path, class:"hm-link text-center" %></li>
          <li class="hm-link text-center"><%= link_to "このサイトについて",about_path,class:"hm-link text-center" %></li>
          <li class="hm-link text-center"><%= link_to "ロードバイク詳細検索", search_bike_path, class:"hm-link text-center" %></li>
          <li class="hm-link text-center"><%= link_to "メーカー一覧", makers_path, class:"hm-link text-center" %></li>
        <% end %>
    </div>
    </ul>
  </nav>
  <nav>
    <div id="hm-icon">
   <%= link_to "#", class:"menu-trigger link" do %>
     <span></span>
     <span></span>
     <span></span>
   <% end %>
  </div>
</nav>
</header>


app/views/layouts/_page-up.html.erb
  <span id="back">
    <a href="#"> <!-- そのページ最上部へのリンク -->
      <%= image_tag("/images/arrow.png", :class => "image_size") %>
    </a>
  </span>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Road-Impression</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.min.js"></script>
    <%= yield %>
  </body>
</html>